

version: '3.1'
services:
  app:
    container_name: booking
    image: booking
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresDB
    environment:
      - DATABASE_PASSWORD=1234
      - DATABASE_USER=postgres
      - DATABASE_URL=jdbc:postgresql://postgresDB:5432/elements

  postgresDB:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=elements